### ISSUE TITLE
How to show the visualization during training

### ISSUE THREAD

**Issue by yani-rl-ai** [robot-learning-freiburg/kinematic-feasibility-rl#2]
Hi @dHonerkamp @avalada i successfully compile and run your project without any error in my local machine, but when i start the main.py program, i got this following message : 

**(modulation_rl) kubotalab@kubotalab:~/catkin_ws_pr2$ python src/modulation_rl/scripts/main.py**
Deleting dir src/modulation_rl/scripts/logs/wandb
Failed to delete dir src/modulation_rl/scripts/logs/wandb: [Errno 2] No such file or directory: 'src/modulation_rl/scripts/logs/wandb'
Deleting dir src/modulation_rl/scripts/logs/mytmp
Failed to delete dir src/modulation_rl/scripts/logs/mytmp: [Errno 2] No such file or directory: 'src/modulation_rl/scripts/logs/mytmp'
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: Offline run mode, not syncing to the cloud.
wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` to enable cloud syncing.
Log path: src/modulation_rl/scripts/logs
Creating pr2[ WARN] [1627891327.183827709]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.

Detected state dim: 29
Actions to learn: ['base_rot', 'base_x', 'base_y']
[ WARN] [1627891327.184974483]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185006713]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185042026]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185123828]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185148033]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185167254]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185180845]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185241062]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185257683]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185267920]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185281195]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185321044]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185335348]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185347306]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185360127]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185414946]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185428103]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185441009]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185455119]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185498489]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185512533]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185529033]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185544851]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185584247]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185596867]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185608907]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185621673]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185694743]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185709708]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185725346]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185737848]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185787135]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185800431]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185813427]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185825707]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185877770]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185893383]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185903576]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185916087]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185957812]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185971085]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.185980692]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186009759]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186043361]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186055346]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186067856]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186083721]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186121790]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186133741]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186145597]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186157207]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186190221]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186203749]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186219024]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186231975]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186259120]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186270358]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186287891]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186301091]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186337495]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186360390]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186378203]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186393678]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186486054]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186509058]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186523422]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186533741]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186542779]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186556401]: Lin[INFO] [1627891328.121493, 270.304000]: Constructing SAC agent
k 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186573937]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186590447]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186614251]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186626611]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186639549]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186656030]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186667058]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186679069]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186690901]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186702483]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186714843]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186726139]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186740459]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186755661]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186768329]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186780020]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186791551]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186802869]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186814457]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186825859]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186837504]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186848876]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186860838]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186871665]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186883599]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186894907]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186906384]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186917619]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186928997]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186940378]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186952462]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186963670]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186975316]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186987420]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.186999702]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187010818]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187022387]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187037239]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187050871]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187062522]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187074366]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187085520]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187097332]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187108524]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187118106]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187129213]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187140706]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187151966]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187164013]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187178707]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187192965]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187204175]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187216113]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187227105]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187239061]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187250323]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187262374]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187290978]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187312174]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187330626]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187351358]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187370052]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187383572]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187394705]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187406432]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187418233]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187431407]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187443029]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187454520]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187465669]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187477728]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187488901]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187500997]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187511948]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187525061]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187534831]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187546995]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187556681]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187566424]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187578549]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187598206]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187619333]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187631273]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187642813]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187655055]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187666330]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187677343]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187690122]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187701177]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187713149]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187728699]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187743304]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187753008]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187766259]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187778739]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187790525]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187806188]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187825230]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187840671]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187858095]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187881620]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187908293]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187933367]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187955497]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.187977953]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188005581]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188052474]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188104904]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188146643]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188168950]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188189490]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188766725]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188789172]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188804976]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188819970]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188836319]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188847968]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188863384]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188878999]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188891145]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188903565]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188923604]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188936145]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188945347]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188956278]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188968847]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188979962]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.188991753]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189002871]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189014894]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189027616]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189037390]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189053886]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189067250]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189078421]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189092834]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189104027]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189116270]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189124878]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189134067]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189149331]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189161759]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189173459]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.189191417]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1627891327.371488713]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/robot_description_kinematics/left_arm/kinematics_solver_attempts' from your configuration.
[ WARN] [1627891327.401292709]: IK plugin for group 'left_arm' relies on deprecated API. Please implement initialize(RobotModel, ...).
[ WARN] [1627891327.434708472, 269.760000000]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ WARN] [1627891327.438960299, 269.762000000]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ WARN] [1627891327.448058872, 269.769000000]: IK plugin for group 'right_arm' relies on deprecated API. Please implement initialize(RobotModel, ...).
[ WARN] [1627891327.477010126, 269.789000000]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ WARN] [1627891327.478278637, 269.789000000]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
/home/kubotalab/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
[INFO] [1627891332.268247, 273.525000]: Start learning loop
[ INFO] [1627891327.190337331]: Loading robot model 'pr2'...
[ INFO] [1627891327.519750965, 269.816000000]: Planning frame: odom_combined
[ INFO] [1627891327.545464439, 269.832000000]: Starting planning scene monitor
[ INFO] [1627891327.547818690, 269.833000000]: Listening to '/my_planning_scene'
[ INFO] [1627891327.548987676, 269.834000000]: Known collision objects:
/home/kubotalab/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/kubotalab/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[ INFO] [1627891341.324226838, 280.342000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891353.127920953, 289.759000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891353.428886892, 289.993000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891359.853093053, 295.090000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891360.185749622, 295.340000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891360.185936916, 295.340000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891362.457969354, 297.092000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891364.392537316, 298.545000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891364.392804579, 298.546000000]: set_start_pose: drawn pose in self-collision, trying again
/home/kubotalab/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/numpy/lib/histograms.py:908: RuntimeWarning: invalid value encountered in true_divide
  return n/db/n.sum(), bin_edges
[INFO] [1627891368.560955, 301.710000]: ---------------------------------------
[INFO] [1627891368.562873, 301.711000]: T 1, eval_rStart_rGoals evaluation over 50 episodes: Avg. return (undisc) -100.114, Avg. return (disc) -48.537, Avg failures 100.00
[INFO] [1627891368.564468, 301.713000]: IK fails: 0.000p < 99, 0.000p < 11, 0.000p < 1
[INFO] [1627891368.565933, 301.714000]: ---------------------------------------
Episode length: 133.48 +/- 32.04
Saving best model
[ INFO] [1627891376.576555824, 307.801000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891385.704186376, 314.759000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891387.812427610, 316.408000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891389.184237296, 317.440000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891398.762592440, 324.594000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891406.136771940, 330.209000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891410.855451851, 333.696000000]: set_start_pose: drawn pose in self-collision, trying again
[ INFO] [1627891410.855629456, 333.696000000]: set_start_pose: drawn pose in self-collision, trying again

**i could not see the Rviz training visualization. i used PR2 env. i load the config on Rviz but nothing happened.**

**Comment by dHonerkamp** [comment]
Hi,

to publish all markers to rviz you have to pass in the `--vis_env` flag to the main.py script.
Let me know if that resolves the issue for you.

Best,
Daniel
